import * as builder from './metalted.builder.js';
//import { Application } from './metalted.application.js';
import { Hangman } from './apps/metalted.hangman.js';

export const commands = {
    'error' : {
        command: () =>
        {
            const cmd = builder.CommandBuilder();
            cmd.CreateChatInputCommand('error', 'This command will produce an error message.');
            return cmd.command;
        }
    },
    'mo' : {
        command: () =>
        {
            const cmd = builder.CommandBuilder();
            cmd.CreateChatInputCommand('mo', 'A simple mo command with options');
            return cmd.command;
        },
        app : (request, userInteractionSystem) =>
        {
            return Hangman(request, userInteractionSystem);
        }
    },
    'User Command' : {
        command: () =>
        {
            const cmd = builder.CommandBuilder();
            cmd.CreateUserCommand('User Command');
            return cmd.command;            
        },
        response: (request) => 
        { 
            return builder.ChatMessage('A response generated by a user command.'); 
        }
    },
    'Message Command' : {
        command: () =>
        {
            const cmd = builder.CommandBuilder();
            cmd.CreateMessageCommand('Message Command');
            return cmd.command;            
        },
        response: (request) => 
        { 
            return builder.ChatMessage('A response generated by a message command.'); 
        }
    }
};